### ISSUE TITLE
Please remove "onfetch" that catching everything (or an option to disable this)

### ISSUE THREAD

**Issue by miflinak** [one-signal/OneSignal-Website-SDK#28]
Hello!
First of all thank you for OneSignal. It's very convenient to use.

My problem is that OneSignal ServiceWorker catching all requests. It seems useless cause it doesn't do anything except fetch. Even more, it's harmful!

In my case it broke all videos on my site. There are two reasons:
1) Seems like "fetch" doesn't allow request to http video from https (while browser allow this).
2) Even if I use https to request video, "fetch" seems like trying to download whole video and video player waiting until it would be done.

So, please remove it or add an option to disable it.

**Comment by jasonpang** [comment]
Hi miflinak,

Sorry about that, we'll add an option to disable the fetch handler. 

We added it because in Mozilla v44, there is a bug that doesn't send the Origin header along with CORS requests when a service worker is active. Because this bug affects all Firefox v44 users, and because we install a service worker on all sites that use us, we implemented the change for all sites.

Original Bugzilla Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1243453

**Comment by jasonpang** [comment]
Hi,

The change has been deployed. In your `OneSignal.push(["init" ...` call, please add an option for:

`serviceWorkerRefetchRequests: false,`
e.g.

`OneSignal.push(["init", {      
      // Your other settings
      appId: "YOUR_APP_ID",
      serviceWorkerRefetchRequests: false,
    }]);`

**Comment by miflinak** [comment]
Thanks!
