### ISSUE TITLE
Add in NPM

### ISSUE THREAD

**Issue by danieljoppi** [one-signal/OneSignal-Website-SDK#34]
You can add your project in NPM?

```bash
npm install onesignal-web-sdk --save
```

**Comment by jasonpang** [comment]
Hey Daniel,

We'll look into this!

**Comment by jasonpang** [comment]
Hey Daniel,

I don't think it'd be a good idea to add our project in NPM or other web module registries. For the meantime, we'd prefer our users to include our SDK via our CDN URL of https://cdn.onesignal.com/sdks/OneSignalSDK.js. 

Our web SDK is tightly connected to our server and product. For HTTP sites, on site load, an iFrame from OneSignal is loaded into the page, and our iFrame loads the above CDN URL to load the web SDK to communicate with the host page. For HTTP sites that are subscribing for push notifications, a popup window is opened which also loads the web SDK from the above CDN URL. Finally, once the user subscribes, a service worker is registered, which once again imports the above CDN URL (the service worker is bundled into our web SDK). Because there are 4 - 5 separate components all pointing to the same CDN URL, installing our web SDK via NPM, Bower, or another provider and forgetting to update would cause a lot of difficult to debug errors. Sometimes our updates don't change much, sometimes our updates change a lot of the SDK. In Chrome 50, for example, I believe the Chrome team is trying to released a major feature to web push that will change the way our service worker receives push notifications entirely, and we will update our web SDK for this eventually. To meet the changing web push standard in addition to fixing bugs, we update the web SDK somewhat frequently.
