### ISSUE TITLE
Firefox 45 not working (Ubuntu)

### ISSUE THREAD

**Issue by plfreudenreich-proximis** [one-signal/OneSignal-Website-SDK#40]
Website SDK isn't working on Firefox 45 (Ubuntu) : 

```
TypeError: window.localStorage is null
 init()
  OneSignalSDK.js:4
 push()
  OneSignalSDK.js:5
 _processPushes()
  OneSignalSDK.js:5
 <anonyme>
  OneSignalSDK.js:1
 __webpack_require__()
  OneSignalSDK.js:1
 <anonyme>
  OneSignalSDK.js:1
 <anonyme>
  OneSignalSDK.js:1
```

**Comment by jasonpang** [comment]
Hello,

Thanks for letting us know! Are you running in Private Browsing Mode in Firefox?

**Comment by plfreudenreich-proximis** [comment]
Hi,

No Private browsing, no ad blocker or similar extensions that couldd block script and local storage.

Just the latest Firefox (45.0) on Ubuntu 14.04.

**Comment by jasonpang** [comment]
Hmm, it's very strange that window.localStorage is null. We were unable to reproduce any issues on Firefox 45 on Ubuntu 14.04.

I was able to overwrite window.localStorage and set it to null using this script on Firefox:

```
Object.defineProperty(window, 'localStorage', {
  value: null
});
```

Would you be able to provide the URL to your site so that we can check for 3rd party scripts possibly overwriting local storage?

Could you also visit this local storage test page and let us know what you see? http://dev-test.nemikor.com/web-storage/support-test/

Here's what my test looks like if local storage is supported:

![image](https://cloud.githubusercontent.com/assets/1015970/14364899/d86cd1cc-fcbf-11e5-9d8f-233ee6cc4716.png)

Here's what my test looks like if I set local storage to null:

```
Object.defineProperty(window, 'localStorage', {
  value: null
});
```
![image](https://cloud.githubusercontent.com/assets/1015970/14364922/f2bd095c-fcbf-11e5-9abc-b112386f52ca.png)

**Comment by jasonpang** [comment]
@plfreudenreich-proximis Do you have any updates to this issue?

**Comment by plfreudenreich-proximis** [comment]
I'm not able to provide you an access to the page used in our private CI.

But I can confirm that the local storage test show me that my Firefox doesn't support this feature for an unknown reason..

Should be a problem on my installation.

**Comment by jasonpang** [comment]
Could be a Firefox profile issue. I've personally encountered some strange bugs with some profiles preventing IndexedDB access or service worker registration.

Could you try this? https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by plfreudenreich-proximis** [comment]
You're right. With a new profile, my local storage is working and then, OneSignal too :+1: 

![image](https://cloud.githubusercontent.com/assets/15922822/14734180/073513b6-0869-11e6-8c93-2350439cdead.png)

My bad. Thanks for support !

**Comment by jasonpang** [comment]
I've had to create three new profiles in the last new months for testing for this reason, so it looks like there's a bug with some somewhere. Glad this resolved it!
